language: python
os: linux
cache: pip
# dist: xenial

matrix:
  include:
    - name: "Python 3.4 on Linux"
      python: 3.4
      env: TOXENV=py34
    - name: "Python 3.5 on Linux"
      python: 3.5
      env: TOXENV=py35
    - name: "Python 3.6 on Linux"
      python: 3.6
      env: TOXENV=py36
    - name: "Python 3.7 on Linux"
      python: 3.7
      env: TOXENV=py37
    - name: "Python 3.8 on Linux"
      dist: xenial
      python: 3.8
      env: TOXENV=py38
      after_success: codecov  # use this version for the tests!
    - name: "Python Nightly on Linux"
      dist: bionic
      python: nightly
      env: TOXENV=py39
    - name: "Pypy 3 on Linux"
      python: pypy3
      env: TOXENV=pypy3
    - name: "Python 3 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
      before_install:
        - sw_vers
        - python3 --version
        - pip3 --version
  allow_failures:
    - python: nightly
    - python: pypy3
  fast_finish: true

before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a

install:
  - pip3 install -U pip
  - pip3 install -U pytest pytest-cov codecov tox
  - if $MINIMAL; then pip3 install -U .;
    else pip3 install -U ".[all]"; fi

script:
  - tox
  # - pytest tests/unit_tests.py --cov=codecov

notifications:
  email:
    on_success: never
    on_failure: change
